### ISSUE TITLE
CSL DD P1 V2 Wheel; AC upgrades, and AMS2 implementation.

### ISSUE THREAD

**Issue by wegreenall** [gotzl/hid-fanatecff-tools#1]
I have implemented some changes for the way it handles Assetto Corsa RPM LED behaviour. The current situation compares to 8000.
I have scraped data from the UI powerCurves in the game to get better Max RPM numbers, as well as improving handshake behaviour to get those numbers at the beginning of the game. Furthermore I have set it to capture the min RPM at game start to get correct upper and lower bounds for the revLightsPercent calculation. 

I have also added an CSLP1V2Wheel class which has proper handling for the way that that wheel presents the RPM light (it has one led zone with different colours, rather than several LEDS). This has also led me to set up a more reasonable function boundary for revLightPercent handling; set_sysfs_rpm now just receives revLightsPercent and decides itself (for the appropriate wheel class) how to display the lights. 

I have also implemented an AMS2 client which seems to work well (via UDP and using Scapy). I would love to know how I might contribute all this to the base (I obviously don't have permission to just push my commits and branches).

Let me know what you'd need for us to be able to add what I've done to the codebase.

**Comment by gotzl** [comment]
Hi there,

happy to see s.o. using/working on this! Your changes sound very good and I surly would like to include them!
The usual github way would be that you create a `fork` of this project. You can commit your changes there (ideally in a development branch) and then create a `pull request`.
Let me know if you need more assistance!

**Comment by wegreenall** [comment]
Thank you for getting back to me! I have made a pull request but I think I may have done it in a way that was a bit clumsy; you might want to pull it to another branch other than master so you can just check it still works for you. I think in my version the default got set to my wheel, so you might need to double check that and of course change it back as you feel appropriate.

It'd be great to just get a check on whether it works for you as well with your CSL Elite wheel so that I know I haven't broken anything (I don't have one of those to test on).

Let me know if you have any comments!

**Comment by gotzl** [comment]
Great! I'll check it out locally to test, maybe modify and merge it. Hope I'll find some time on the weekend. Anyways, thanks for contributing!

**Comment by gotzl** [comment]
So, I had a brief look. The bulk of things looks real good, but there are some things that I think need to be changed, eg the hardcoded NIC name (can't this not just listen on localhost?). I can do these changes myself, or I can do a review and point out these things for you to change. What do you prefer?

**Comment by wegreenall** [comment]
I prefer the latter, and I can also make some small edits as I have found a
couple of mistakes in the meantime. Thanks very much for taking the time!

**Comment by gotzl** [comment]
Would you update the PR so that I can review your latest version? Ty.

**Comment by wegreenall** [comment]
I have pushed latest changes - just to fix clearing of gears on game close
on AMS2 (and put appropriate display on P1V2Wheel as it doesn't have a
reverse display).
Can't get clearing of gears on AC, don't know if you have any insight.
Please let me know how and what you'd like me to do.

**Comment by gotzl** [comment]
So, I've applied some changes on top of your changes. Most notably, I found out in the `hid-fanatecff` part, that wheel-ids are actually only 2bytes. I've then also added mappings for my wheel. Now, for me, the AC upgrades as well as the AMS2 impl works fine, together with the latest `hid-fanatecff` code. I'll close this when some time has passed and no one comes to complain ;)
