### ISSUE TITLE
Fanatec_led_server.py error handling

### ISSUE THREAD

**Issue by SynthetikzZ** [gotzl/hid-fanatecff-tools#5]
hello again,

so i wrote me a simple service file for the fanatec led server act as a systemd service

looks like this
```

[Unit]
Description=Runs the Fanatec LED Server on Startup as root

[Service]
ExecStart=/usr/bin/python3 fanatec_led_server.py --device 0020 --display gear
WorkingDirectory=/path/to/hid-fanatecff-tools/tools/
Restart=always

[Install]
WantedBy=multi-user.target

```

placed in /etc/systemd/system/fanatecled.service

and then enabled and started like any other systemd service

to really work as a service running in the background it has to handle wheelbase disconnects properly. if the wheelbase disconnects in the current state, then i get following exception:
```

Dez 12 21:24:56 synthetikz-pc python3[724]: Exception in thread Thread-4:
Dez 12 21:24:56 synthetikz-pc python3[724]: Traceback (most recent call last):
Dez 12 21:24:56 synthetikz-pc python3[724]:   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Dez 12 21:24:56 synthetikz-pc python3[724]:     self.run()
Dez 12 21:24:56 synthetikz-pc python3[724]:   File "/home/synthetikz/Schreibtisch/msc/hid-fanatecff-tools/tools/fanatec_led_server.py", line 147, in run
Dez 12 21:24:56 synthetikz-pc python3[724]:     open(display, 'w').write(display_val)
Dez 12 21:24:56 synthetikz-pc python3[724]:     ^^^^^^^^^^^^^^^^^^
Dez 12 21:24:56 synthetikz-pc python3[724]: FileNotFoundError: [Errno 2] No such file or directory: '/sys/module/hid_fanatec/drivers/hid:ftec_csl_elite/0003:0EB7:0020.00>
```

i noticed that you have already an exception handling at line 119 in fanatec_led_server.py that only executes break.

i tested starting the server before i power on my wheelbase and it picks up fine on powering on so i assume it waits for a wheelbase to connect right ?  it should be possible then that the script falls back into waiting for connection mode instead of braking right ? 

is there a simple fix you could add in ?

thank you 

edit: little question. would it be possible, that if the wheelbase disconnects, the driver would somehow wait for it to reconnect so the game picks it up immediatly with ffb and stuff without to having to restarting the game ?

**Comment by SynthetikzZ** [comment]
i got it working on my own yeees

on line 147 you have
`open(display, 'w').write(display_val)`


i made it 
```

                    try:
                        open(display, 'w').write(display_val)
                    except Exception as e:
                        self.run()


```


now it works as a service in the background for me even if connection drops out, the fanatec led server picks up again as soon as it reconnects


now the next thing that is alittle bit annoying is the constantly white flashing led if not in a car... could be a subtle color like blue :D

**Comment by gotzl** [comment]
Hello,
I've fixed the issue a along with some other slight changes, plz give it a try!

> placed in /etc/systemd/system/fanatecled.service

So, if this runs as system service, you should really add `User=` and `Group=` to the service file. Random repos from the internet should never run as root user! To help with that, I've already checked-in some udev rule changes on the driver side. With them, it should be enough if the user that runs the server is in the `games` group.

> edit: little question. would it be possible, that if the wheelbase disconnects, the driver would somehow wait for it to reconnect so the game picks it up immediatly with ffb and stuff without to having to restarting the game ?

I don't think I can do s.t. different here on the driver side. This is all things handled by wine (proton) and the game itself. That said, I also don't see the use case here? Do you want to interchange wheelbases mid-game?

> now the next thing that is alittle bit annoying is the constantly white flashing led if not in a car... could be a subtle color like blue :D

What game is this? And which wheel do you have? Maybe this will be fixed when #2 is merged - this includes some changes to led coloring ...

**Comment by SynthetikzZ** [comment]
csl p1 v2 wheel. i think this could be due to no max rpm available so it flashes in white because it thinks its in the rev limiter. happens in both acc and rf2 for me.

**Comment by SynthetikzZ** [comment]
with your changes i get following error now 

```
Traceback (most recent call last):
  File "/home/synthetikz/Schreibtisch/msc/hid-fanatecff-tools/tools/./fanatec_led_server.py", line 162, in <module>
    from f1_2020 import F12020Client
  File "/home/synthetikz/Schreibtisch/msc/hid-fanatecff-tools/tools/f1_2020.py", line 7, in <module>
    from f1_2020_telemetry.f1_2020_telemetry import packets
ModuleNotFoundError: No module named 'f1_2020_telemetry.f1_2020_telemetry'
```
i dont even have f1 but i think thats due to something else



ahh myy bad didnt do --recurse-submodules while pulling. now everything works  and it even doesnt blink anymore if not in car! thank you

**Comment by SynthetikzZ** [comment]
Could you implement  OS stop request handling ?

When rebooting or powering off my machine, it halts for two minutes because it can't stop the service. 


Thank you <3
